version: 2

before:
  hooks:
    - go mod download

builds:
  - id: "gb-darwin"
    main: ./
    binary: bin/gb
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/bitdaddy89/gb/version.Name=gb -X github.com/bitdaddy89/gb/version.Version={{.Version}} -X github.com/bitdaddt89/gb/version.Commit={{.Commit}}
  - id: "gb-linux-arm64"
    main: ./
    binary: bin/gb
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/bitdaddy89/gb/version.Name=gb -X github.com/bitdaddy89/gb/version.Version={{.Version}} -X github.com/bitdaddt89/gb/version.Commit={{.Commit}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - gb-darwin
      - gb-linux-arm64
  
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapshot:
  name_template: "{{ .Tag }}-{{ .Branch }}@{{ .ShortCommit }}-{{ .GitTreeState }}"
